# version: "3.8"
services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always